# Welcome to Jekyll!
#
# YAT Theme Configuration for Seungpil Lee's Academic Website
#
# This config file is meant for settings that affect your whole site.
# For technical reasons, this file is *NOT* reloaded automatically when you
# use 'bundle exec jekyll serve'. If you change this file, please restart
# the server process.

# Site settings
title: Seungpil Lee
email: iamseungpil@gm.gist.ac.kr
author: Seungpil Lee
description: >-
  Master student in Gwangju Institute of Science and Technology.
  Research interests: Brain-inspired AI, NLP, Reinforcement Learning,
  Cognitive Science, and Abstract Reasoning.

baseurl: ""
url: "https://iamseungpil.github.io"
repository: "iamseungpil/iamseungpil.github.io"

# Copyright setting
copyright: "© 2024-{currentYear} {author}"

# Yat date format
yat:
  date_format: "%b %d, %Y"

# Site configuration
header_transparent: true
content_width: "920px"

# Night/Dark mode
night_mode: "auto"

# Header pages
header_pages:
  - about.html

# Pagination
paginate: 5

# Build settings
theme: jekyll-theme-yat
highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo

# Collections - Academic content
collections:
  publications:
    output: true
    permalink: /publication/:path/

# Defaults
defaults:
  - scope:
      path: ""
      type: publications
    values:
      layout: post
      author_profile: false
  - scope:
      path: ""
      type: posts
    values:
      layout: post

# Plugins
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-spaceship

# Include/Exclude files
include:
  - _pages
  - _publications
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor

# Reading Files
encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"
